language: python
python:
  - "3.6"
before_install:
  - "export COMMIT_ID=\"$(git log --format=%H -n 1)\""
  - "export COMMIT_MSG=\"$(git log --format=%B -n 1)\""
install:
  - pip install twine
  - python ./setup.py sdist
  - twine upload --repository pypi --username ${USER} --password ${PASS} --comment "${COMMIT_MSG} (${COMMIT_ID})" --skip-existing ./dist/*
branches:
  only:
    - production
    - master
script:
  - echo "TODO"