language: python
python:
  - "3.6"
before_install:
  - "export COMMIT_ID=\"$(git log --format=%H -n 1)\""
  - "export COMMIT_MSG=\"$(git log --format=%B -n 1)\""
  - "export GIT_BRANCH=${TRAVIS_BRANCH}"
install:
  - pip install twine==1.11.0 setuptools==39.2.0 wheel==0.31.1 tox===3.0.0 coveralls
branches:
  only:
    - production
    - testing
    - master
script:
    - tox
    - python ./setup.py sdist
    - twine upload --repository pypi --username ${TWINE_USERNAME} --password ${TWINE_PASS} --comment "${COMMIT_MSG} (${COMMIT_ID})" --skip-existing ./dist/*
after_script:
    - coveralls
notifications:
    email: false